"""
aeam/agents/rag/query_expansion.py

LLM-based query expansion for Multi-Query Retrieval (Phase 7.3).

Given a single user/investigation query, generates several semantically
diverse reformulations so :class:`~aeam.agents.rag.multi_query_retrieval.MultiQueryRetrievalPipeline`
can retrieve under multiple phrasings/angles of the same incident and fuse
the results — recovering relevant chunks that one phrasing alone would miss.

Design constraints (Phase 7.3):
- Never breaks the pipeline: any LLM failure or unparsable/empty output
  degrades to ``[original_query]`` (single-query passthrough), never raises.
- The original query is always preserved as element 0 of the returned list
  (requirement #2) — expansion only ever ADDS queries, never replaces it.
- Reuses the shared, hardened JSON parser (:func:`aeam.agents.rag.rag_agent.parse_llm_json`,
  introduced in Phase 6) instead of a new ad-hoc parser.
- No new framework — plain ``llm_service.query(...)`` call, same protocol
  RAGAgent already uses.
"""

from __future__ import annotations

from typing import Any

from aeam.agents.rag.rag_agent import parse_llm_json
from aeam.monitoring.logging_config import get_logger

logger = get_logger(__name__, agent="rag")

DEFAULT_QUERY_COUNT: int = 4
_TEMPERATURE: float = 0.3
_MAX_TOKENS: int = 300


class QueryExpansionAgent:
    """
    Generates diverse retrieval-query variants for Multi-Query Retrieval.

    Args:
        llm_service:  Service satisfying ``query(prompt, *, temperature, max_tokens) -> str``
                      (the same protocol :class:`~aeam.agents.rag.rag_agent.RAGAgent` uses).
        query_count:  Total number of queries to use for retrieval, INCLUDING
                      the original — i.e. up to ``query_count - 1`` variants are
                      generated by the LLM. Must be >= 1. When 1, the LLM is
                      never called (config-level equivalent of disabling expansion).

    Raises:
        ValueError: If ``llm_service`` is None or ``query_count`` < 1.
    """

    def __init__(self, llm_service: Any, query_count: int = DEFAULT_QUERY_COUNT) -> None:
        if llm_service is None:
            raise ValueError("llm_service must not be None.")
        if query_count < 1:
            raise ValueError(f"query_count must be >= 1. Got: {query_count}.")
        self._llm = llm_service
        self._query_count = query_count

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def expand(self, original_query: str) -> list[str]:
        """
        Return a list of retrieval queries, with ``original_query`` always first.

        Steps:
        1. If ``query_count <= 1``, skip the LLM entirely — return
           ``[original_query]``.
        2. Otherwise, ask the LLM for up to ``query_count - 1`` diverse
           reformulations as ``{"queries": [...]}``.
        3. Parse with the shared resilient parser; filter to non-empty
           strings; drop anything duplicating (case-insensitively) an
           already-selected query; cap at ``query_count - 1``.
        4. On any failure (LLM exception, unparsable response, zero usable
           variants) — return ``[original_query]`` only. Never raises.

        Args:
            original_query: The query to expand. Must be non-empty.

        Returns:
            List of 1..``query_count`` query strings, element 0 always equal
            to ``original_query`` (stripped).

        Raises:
            ValueError: If ``original_query`` is empty or whitespace-only.
        """
        if not original_query or not original_query.strip():
            raise ValueError("original_query must be a non-empty string.")

        original = original_query.strip()
        queries: list[str] = [original]

        if self._query_count <= 1:
            return queries

        n_variants = self._query_count - 1
        try:
            raw = self._llm.query(
                self._build_prompt(original, n_variants),
                temperature=_TEMPERATURE,
                max_tokens=_MAX_TOKENS,
            )
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "QueryExpansionAgent | LLM call failed (%s) — falling back to "
                "original query only.", exc,
            )
            return queries

        parsed = parse_llm_json(raw)
        if parsed is None:
            logger.warning(
                "QueryExpansionAgent | could not parse LLM response as JSON — "
                "falling back to original query only."
            )
            return queries

        candidates = parsed.get("queries", [])
        if not isinstance(candidates, list):
            logger.warning(
                "QueryExpansionAgent | 'queries' was not a list (%s) — "
                "falling back to original query only.", type(candidates).__name__,
            )
            return queries

        seen_lower = {original.lower()}
        for candidate in candidates:
            if len(queries) - 1 >= n_variants:
                break
            if not isinstance(candidate, str):
                continue
            text = candidate.strip()
            if not text or text.lower() in seen_lower:
                continue
            queries.append(text)
            seen_lower.add(text.lower())

        if len(queries) == 1:
            logger.warning(
                "QueryExpansionAgent | LLM returned zero usable variants — "
                "using original query only."
            )
        else:
            logger.info(
                "QueryExpansionAgent | expanded 1 -> %d queries.", len(queries),
            )
        return queries

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _build_prompt(original_query: str, n_variants: int) -> str:
        return (
            "You are helping a site-reliability engineer search an incident "
            "knowledge base. Given the search query below, generate "
            f"{n_variants} alternative search queries that are semantically "
            "diverse — different phrasing, synonyms, or a different angle on "
            "the same underlying incident (e.g. symptom-focused vs "
            "cause-focused vs component-focused). Do NOT invent new facts or "
            "unrelated topics; only rephrase.\n\n"
            f"Original query: {original_query!r}\n\n"
            "Return ONLY a valid JSON object, no other text, with this exact shape:\n"
            '{"queries": ["<variant 1>", "<variant 2>", ...]}'
        )

    def __repr__(self) -> str:
        return f"QueryExpansionAgent(query_count={self._query_count})"
